/*
 * Copyright (c) Chris Wohlgemuth 2002 
 * All rights reserved.
 *
 * http://www.geocities.com/SiliconValley/Sector/5785/
 * http://www.os2world.com/cdwriting
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The authors name may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 */
/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.42
 */

#ifndef SOM_Module_cwhelp_Source
#define SOM_Module_cwhelp_Source
#endif
#define CWHelp_Class_Source
#define M_CWHelp_Class_Source
#include <os2.h>
#include "cwhelp.ih"


SOM_Scope BOOL  SOMLINK cwhelp_wpSetup(CWHelp *somSelf, PSZ pszSetupString)
{
  ULONG bSize;
  char buffer[CCHMAXPATH];

    CWHelpData *somThis = CWHelpGetData(somSelf);
    CWHelpMethodDebug("CWHelp","cwhelp_wpSetup");

    /* User sends the help library name */
    bSize=sizeof(_chrHelpLib);
    if(_wpScanSetupString(somSelf, pszSetupString, "HLPSETHELPLIBRARY", _chrHelpLib, &bSize))
      _chrHelpLib[sizeof(_chrHelpLib)-1]=0;

    /* User requests help */
    bSize=sizeof(_chrHelpLib);
    if(_wpScanSetupString(somSelf, pszSetupString, "HLPSHOWHELPPANEL", buffer, &bSize))
      {
        ULONG ulHlpPanel=atol(buffer);/* The help panel */
        _wpDisplayHelp(somSelf, ulHlpPanel, _chrHelpLib);/* Show it */
      }    

    return (CWHelp_parent_WPTransient_wpSetup(somSelf, pszSetupString));
}


SOM_Scope PSZ  SOMLINK cwhelpM_wpclsQueryTitle(M_CWHelp *somSelf)
{
    /* M_CWHelpData *somThis = M_CWHelpGetData(somSelf); */
    M_CWHelpMethodDebug("M_CWHelp","cwhelpM_wpclsQueryTitle");

    return "Help tool (CWHelp)";
}

