
/*
 * This file was generated by the SOM Compiler.
 * FileName: cwhelp.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

/*
 * 
 * Copyright (c) Chris Wohlgemuth 2002
 * All rights reserved.
 * 
 * http://www.geocities.com/SiliconValley/Sector/5785/
 * http://www.os2world.com/cdwriting
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The authors name may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * 
 * 
 * cwhelp.idl
 */


#ifndef SOM_CWHelp_h
#define SOM_CWHelp_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef CWHelp
#define CWHelp SOMObject
#endif
#include <wptrans.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPTransient
    #define M_WPTransient SOMObject
#endif /* M_WPTransient */
#ifndef M_CWHelp
    #define M_CWHelp SOMObject
#endif /* M_CWHelp */

/*
 * End of user-defined types.
 */

#define CWHelp_MajorVersion 1
#define CWHelp_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define CWHelpNewClass cwhelpc
#pragma linkage(cwhelpc, system)
#define CWHelpClassData cwhelpd
#define CWHelpCClassData cwhelpx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <cwhelp.h>
/*--------------Migration------------*/
#define CWHelp_classObj CWHelpClassData.classObject
#define _CWHelp CWHelp_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK CWHelpNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(CWHelpNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct CWHelpClassDataStructure {
	SOMClass *classObject;
} SOMDLINK CWHelpClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct CWHelpCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK CWHelpCClassData;

/*
 * New and Renew macros for CWHelp
 */
#define CWHelpNew() \
   (_somNew(_CWHelp ? _CWHelp : CWHelpNewClass(CWHelp_MajorVersion, CWHelp_MinorVersion)))
#define CWHelpRenew(buf) \
   (_somRenew(_CWHelp ? _CWHelp : CWHelpNewClass(CWHelp_MajorVersion, CWHelp_MinorVersion), buf))

/*
 * Override method: wpSetup
 */
#define CWHelp_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define CWHelp_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define CWHelp_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define CWHelp_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define CWHelp_wpAddSettingsPages WPObject_wpAddSettingsPages
#define CWHelp_wpAddToObjUseList WPObject_wpAddToObjUseList
#define CWHelp_wpAllocMem WPObject_wpAllocMem
#define CWHelp_wpAppendObject WPObject_wpAppendObject
#define CWHelp_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define CWHelp_wpClose WPObject_wpClose
#define CWHelp_wpCnrInsertObject WPObject_wpCnrInsertObject
#define CWHelp_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define CWHelp_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define CWHelp_wpConfirmDelete WPObject_wpConfirmDelete
#define CWHelp_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define CWHelp_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define CWHelp_wpCopyObject WPObject_wpCopyObject
#define CWHelp_wpCreateAnother WPObject_wpCreateAnother
#define CWHelp_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define CWHelp_wpCreateShadowObject WPObject_wpCreateShadowObject
#define CWHelp_wpDelete WPObject_wpDelete
#define CWHelp_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define CWHelp_wpDisplayHelp WPObject_wpDisplayHelp
#define CWHelp_wpDisplayMenu WPObject_wpDisplayMenu
#define CWHelp_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define CWHelp_wpDraggedOverObject WPObject_wpDraggedOverObject
#define CWHelp_wpDragOver WPObject_wpDragOver
#define CWHelp_wpDrop WPObject_wpDrop
#define CWHelp_wpDroppedOnObject WPObject_wpDroppedOnObject
#define CWHelp_wpEndConversation WPObject_wpEndConversation
#define CWHelp_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define CWHelp_wpFindUseItem WPObject_wpFindUseItem
#define CWHelp_wpFormatDragItem WPObject_wpFormatDragItem
#define CWHelp_wpFree WPObject_wpFree
#define CWHelp_wpFreeMem WPObject_wpFreeMem
#define CWHelp_wpHide WPObject_wpHide
#define CWHelp_wpInitData WPObject_wpInitData
#define CWHelp_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define CWHelp_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define CWHelp_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define CWHelp_wpMenuItemSelected WPObject_wpMenuItemSelected
#define CWHelp_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define CWHelp_wpMoveObject WPObject_wpMoveObject
#define CWHelp_wpOpen WPObject_wpOpen
#define CWHelp_wpPrintObject WPObject_wpPrintObject
#define CWHelp_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define CWHelp_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define CWHelp_wpQueryConfirmations WPObject_wpQueryConfirmations
#define CWHelp_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define CWHelp_wpQueryDefaultView WPObject_wpQueryDefaultView
#define CWHelp_wpQueryDetailsData WPObject_wpQueryDetailsData
#define CWHelp_wpQueryError WPObject_wpQueryError
#define CWHelp_wpSetFolder WPObject_wpSetFolder
#define CWHelp_wpQueryFolder WPObject_wpQueryFolder
#define CWHelp_wpQueryIcon WPObject_wpQueryIcon
#define CWHelp_wpQueryIconData WPObject_wpQueryIconData
#define CWHelp_wpQueryMinWindow WPObject_wpQueryMinWindow
#define CWHelp_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define CWHelp_wpQueryStyle WPObject_wpQueryStyle
#define CWHelp_wpSetTaskRec WPObject_wpSetTaskRec
#define CWHelp_wpFindTaskRec WPObject_wpFindTaskRec
#define CWHelp_wpQueryTitle WPObject_wpQueryTitle
#define CWHelp_wpRegisterView WPObject_wpRegisterView
#define CWHelp_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define CWHelp_wpRender WPObject_wpRender
#define CWHelp_wpRenderComplete WPObject_wpRenderComplete
#define CWHelp_wpReplaceObject WPObject_wpReplaceObject
#define CWHelp_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define CWHelp_wpRestore WPObject_wpRestore
#define CWHelp_wpRestoreData WPObject_wpRestoreData
#define CWHelp_wpRestoreLong WPObject_wpRestoreLong
#define CWHelp_wpRestoreState WPObject_wpRestoreState
#define CWHelp_wpRestoreString WPObject_wpRestoreString
#define CWHelp_wpSaveData WPObject_wpSaveData
#define CWHelp_wpSaveImmediate WPObject_wpSaveImmediate
#define CWHelp_wpSaveDeferred WPObject_wpSaveDeferred
#define CWHelp_wpSaveLong WPObject_wpSaveLong
#define CWHelp_wpSaveState WPObject_wpSaveState
#define CWHelp_wpSaveString WPObject_wpSaveString
#define CWHelp_wpScanSetupString WPObject_wpScanSetupString
#define CWHelp_wpSetConcurrentView WPObject_wpSetConcurrentView
#define CWHelp_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define CWHelp_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define CWHelp_wpSetDefaultView WPObject_wpSetDefaultView
#define CWHelp_wpSetError WPObject_wpSetError
#define CWHelp_wpSetIconHandle WPObject_wpSetIconHandle
#define CWHelp_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define CWHelp_wpSetupOnce WPObject_wpSetupOnce
#define CWHelp_wpSetIcon WPObject_wpSetIcon
#define CWHelp_wpSetIconData WPObject_wpSetIconData
#define CWHelp_wpSetMinWindow WPObject_wpSetMinWindow
#define CWHelp_wpSetStyle WPObject_wpSetStyle
#define CWHelp_wpModifyStyle WPObject_wpModifyStyle
#define CWHelp_wpSetTitle WPObject_wpSetTitle
#define CWHelp_wpSwitchTo WPObject_wpSwitchTo
#define CWHelp_wpUnInitData WPObject_wpUnInitData
#define CWHelp_wpViewObject WPObject_wpViewObject
#define CWHelp_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define CWHelp_wpQueryHandle WPObject_wpQueryHandle
#define CWHelp_wpUnlockObject WPObject_wpUnlockObject
#define CWHelp_wpObjectReady WPObject_wpObjectReady
#define CWHelp_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define CWHelp_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define CWHelp_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define CWHelp_wpIsDeleteable WPObject_wpIsDeleteable
#define CWHelp_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define CWHelp_wpSetObjectID WPObject_wpSetObjectID
#define CWHelp_wpQueryObjectID WPObject_wpQueryObjectID
#define CWHelp_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define CWHelp_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define CWHelp_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define CWHelp_wpFindViewItem WPObject_wpFindViewItem
#define CWHelp_wpLockObject WPObject_wpLockObject
#define CWHelp_wpIsLocked WPObject_wpIsLocked
#define CWHelp_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define CWHelp_wpWaitForClose WPObject_wpWaitForClose
#define CWHelp_somDefaultInit SOMObject_somDefaultInit
#define CWHelp_somDestruct SOMObject_somDestruct
#define CWHelp_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define CWHelp_somDefaultAssign SOMObject_somDefaultAssign
#define CWHelp_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define CWHelp_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define CWHelp_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define CWHelp_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define CWHelp_somDefaultVAssign SOMObject_somDefaultVAssign
#define CWHelp_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define CWHelp_somInit SOMObject_somInit
#define CWHelp_somFree SOMObject_somFree
#define CWHelp_somUninit SOMObject_somUninit
#define CWHelp_somGetClass SOMObject_somGetClass
#define CWHelp_somGetClassName SOMObject_somGetClassName
#define CWHelp_somGetSize SOMObject_somGetSize
#define CWHelp_somIsA SOMObject_somIsA
#define CWHelp_somIsInstanceOf SOMObject_somIsInstanceOf
#define CWHelp_somRespondsTo SOMObject_somRespondsTo
#define CWHelp_somDispatch SOMObject_somDispatch
#define CWHelp_somClassDispatch SOMObject_somClassDispatch
#define CWHelp_somCastObj SOMObject_somCastObj
#define CWHelp_somResetObj SOMObject_somResetObj
#define CWHelp_somDispatchV SOMObject_somDispatchV
#define CWHelp_somDispatchL SOMObject_somDispatchL
#define CWHelp_somDispatchA SOMObject_somDispatchA
#define CWHelp_somDispatchD SOMObject_somDispatchD
#define CWHelp_somPrintSelf SOMObject_somPrintSelf
#define CWHelp_somDumpSelf SOMObject_somDumpSelf
#define CWHelp_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_CWHelp_h */

#ifndef SOM_M_CWHelp_h
#define SOM_M_CWHelp_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_CWHelp
#define M_CWHelp SOMObject
#endif
#include <wptrans.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define M_CWHelp_MajorVersion 1
#define M_CWHelp_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_CWHelpNewClass cwhelpMc
#pragma linkage(cwhelpMc, system)
#define M_CWHelpClassData cwhelpMd
#define M_CWHelpCClassData cwhelpMx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_CWHelp_classObj M_CWHelpClassData.classObject
#define _M_CWHelp M_CWHelp_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_CWHelpNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_CWHelpNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_CWHelpClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_CWHelpClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_CWHelpCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_CWHelpCClassData;

/*
 * New and Renew macros for M_CWHelp
 */
#define M_CWHelpNew() \
   (_somNew(_M_CWHelp ? _M_CWHelp : M_CWHelpNewClass(M_CWHelp_MajorVersion, M_CWHelp_MinorVersion)))
#define M_CWHelpRenew(buf) \
   (_somRenew(_M_CWHelp ? _M_CWHelp : M_CWHelpNewClass(M_CWHelp_MajorVersion, M_CWHelp_MinorVersion), buf))

/*
 * Override method: wpclsQueryTitle
 */
#define M_CWHelp_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_CWHelp_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_CWHelp_wpclsInitData M_WPObject_wpclsInitData
#define M_CWHelp_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_CWHelp_wpclsNew M_WPObject_wpclsNew
#define M_CWHelp_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_CWHelp_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_CWHelp_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_CWHelp_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_CWHelp_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_CWHelp_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_CWHelp_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_CWHelp_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_CWHelp_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_CWHelp_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_CWHelp_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_CWHelp_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_CWHelp_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_CWHelp_wpclsSetError M_WPObject_wpclsSetError
#define M_CWHelp_wpclsQueryError M_WPObject_wpclsQueryError
#define M_CWHelp_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_CWHelp_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_CWHelp_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_CWHelp_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_CWHelp_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_CWHelp_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_CWHelp_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_CWHelp_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_CWHelp_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_CWHelp_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_CWHelp_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_CWHelp_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_CWHelp_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_CWHelp__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_CWHelp__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_CWHelp__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_CWHelp__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_CWHelp_somNew SOMClass_somNew
#define M_CWHelp_somNewNoInit SOMClass_somNewNoInit
#define M_CWHelp_somRenew SOMClass_somRenew
#define M_CWHelp_somRenewNoInit SOMClass_somRenewNoInit
#define M_CWHelp_somRenewNoZero SOMClass_somRenewNoZero
#define M_CWHelp_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_CWHelp_somAllocate SOMClass_somAllocate
#define M_CWHelp_somDeallocate SOMClass_somDeallocate
#define M_CWHelp__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_CWHelp__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_CWHelp_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_CWHelp_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_CWHelp_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_CWHelp_somInitClass SOMClass_somInitClass
#define M_CWHelp_somInitMIClass SOMClass_somInitMIClass
#define M_CWHelp_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_CWHelp_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_CWHelp_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_CWHelp_somClassReady SOMClass_somClassReady
#define M_CWHelp_somGetApplyStub SOMClass_somGetApplyStub
#define M_CWHelp_somGetClassData SOMClass_somGetClassData
#define M_CWHelp_somSetClassData SOMClass_somSetClassData
#define M_CWHelp_somGetClassMtab SOMClass_somGetClassMtab
#define M_CWHelp_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_CWHelp_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_CWHelp_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_CWHelp_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_CWHelp_somGetMemberToken SOMClass_somGetMemberToken
#define M_CWHelp_somGetMethodData SOMClass_somGetMethodData
#define M_CWHelp_somGetRdStub SOMClass_somGetRdStub
#define M_CWHelp_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_CWHelp_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_CWHelp_somGetMethodToken SOMClass_somGetMethodToken
#define M_CWHelp_somGetName SOMClass_somGetName
#define M_CWHelp_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_CWHelp_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_CWHelp_somGetNumMethods SOMClass_somGetNumMethods
#define M_CWHelp_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_CWHelp_somGetParent SOMClass_somGetParent
#define M_CWHelp_somGetParents SOMClass_somGetParents
#define M_CWHelp_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_CWHelp_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_CWHelp_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_CWHelp_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_CWHelp_somFindMethod SOMClass_somFindMethod
#define M_CWHelp_somFindMethodOk SOMClass_somFindMethodOk
#define M_CWHelp_somFindSMethod SOMClass_somFindSMethod
#define M_CWHelp_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_CWHelp_somLookupMethod SOMClass_somLookupMethod
#define M_CWHelp_somCheckVersion SOMClass_somCheckVersion
#define M_CWHelp_somDescendedFrom SOMClass_somDescendedFrom
#define M_CWHelp_somSupportsMethod SOMClass_somSupportsMethod
#define M_CWHelp_somDefinedMethod SOMClass_somDefinedMethod
#define M_CWHelp_somOverrideMtab SOMClass_somOverrideMtab
#define M_CWHelp_somDefaultInit SOMObject_somDefaultInit
#define M_CWHelp_somDestruct SOMObject_somDestruct
#define M_CWHelp_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_CWHelp_somDefaultAssign SOMObject_somDefaultAssign
#define M_CWHelp_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_CWHelp_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_CWHelp_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_CWHelp_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_CWHelp_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_CWHelp_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_CWHelp_somInit SOMObject_somInit
#define M_CWHelp_somFree SOMObject_somFree
#define M_CWHelp_somUninit SOMObject_somUninit
#define M_CWHelp_somGetClass SOMObject_somGetClass
#define M_CWHelp_somGetClassName SOMObject_somGetClassName
#define M_CWHelp_somGetSize SOMObject_somGetSize
#define M_CWHelp_somIsA SOMObject_somIsA
#define M_CWHelp_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_CWHelp_somRespondsTo SOMObject_somRespondsTo
#define M_CWHelp_somDispatch SOMObject_somDispatch
#define M_CWHelp_somClassDispatch SOMObject_somClassDispatch
#define M_CWHelp_somCastObj SOMObject_somCastObj
#define M_CWHelp_somResetObj SOMObject_somResetObj
#define M_CWHelp_somDispatchV SOMObject_somDispatchV
#define M_CWHelp_somDispatchL SOMObject_somDispatchL
#define M_CWHelp_somDispatchA SOMObject_somDispatchA
#define M_CWHelp_somDispatchD SOMObject_somDispatchD
#define M_CWHelp_somPrintSelf SOMObject_somPrintSelf
#define M_CWHelp_somDumpSelf SOMObject_somDumpSelf
#define M_CWHelp_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_CWHelp_h */
